es.logger.level: INFO
rootLogger: ${es.logger.level}, file
logger:
  # log action execution errors for easier debugging
  action: DEBUG

  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN


  org.apache.http: INFO


additivity:
  index.search.slowlog: false
  index.indexing.slowlog: false
  deprecation: false

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %.10000m%n"
